---
# Dev and prod are co-located on the same VPS. If this changes, update ansible_host here.
all:
  hosts:
    vps:
      ansible_host: sleev-vps
      ansible_user: root
      ansible_ssh_private_key_file: "~/.ssh/id_ed25519"
